monolog:
    handlers:
        requests:
            type: stream
            path: "%env(default:kernel.logs_dir:LOG_DIR)%/requests.log"
            level: info
            channels: [ requests ]
        responses:
            type: stream
            path: "%env(default:kernel.logs_dir:LOG_DIR)%/responses.log"
            level: info
            channels: [ responses ]
        exceptions:
            type: stream
            path: "%env(default:kernel.logs_dir:LOG_DIR)%/exceptions.log"
            level: critical
            channels: [ exceptions ]
        database_queries:
            type: stream
            path: "%env(default:kernel.logs_dir:LOG_DIR)%/database_queries.log"
            level: info
            channels: [ database_queries ]

    channels:
        - requests
        - responses
        - exceptions
        - database_queries
        - deprecation # Deprecations are logged in the dedicated "deprecation" channel when it exists
